name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - next-major
      - '*.x' # maintenance releases branches

jobs:
  Release:
    name: 🚀 Release 🚀
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test --if-present

      - name: Build
        run: npm run build --if-present

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.4
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GIT_AUTHOR_NAME: ${{ secrets.GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
