name: Test Release

on:
  pull_request:
    branches:
      - main
      - dev
      - beta
      - next
      - next-major
      - "*.x" # maintenance releases branches

jobs:
  Test-Release:
    name: 🚀 Test Release 🚀
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Setup node
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: 🚀 Release Dry Run
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true
          ci: false
          branches: |
            [
              'main',
              'dev',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
